### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by iaroel** [Softlabs/xero-laravel#4]
Hi Paul,

Are you still planning to release Laravel 5 package?

**Comment by pauljohnston** [comment]
Hi @iaroel,

Yes, @pricecurrent has just started working on it - I will let you know when its ready.

It will initially be release as dev - would you mind testing it on your app and giving us feedback of any issues? This will help to get the dev flag removed faster.

Thanks

Paul

**Comment by iaroel** [comment]
Hi Paul,

Thanks for the quick reply.
Sure I'll download and start testing today.

Have a great day.

Erol

**Comment by pauljohnston** [comment]
Hi Erol,

I tested v3.0.2 and it worked for me so I will close this issue - if you have any problems just raise another issue.

Regards

Paul
