### ISSUE TITLE
Laravel 5 support

### ISSUE THREAD

**Issue by iaroel** [Softlabs/xero-laravel#5]
Hi Paul,

I've just installed the v3 release I'm getting following error message.

FatalErrorException in PHPXero.php line 998:
syntax error, unexpected 'class' (T_CLASS), expecting identifier (T_STRING) or variable (T_VARIABLE) or '{' or '$'

**Comment by pricecurrent** [comment]
Hi Erol!

I took a look at the issue and it's fixed now. We just need to wait for Paul to release.

**Comment by pauljohnston** [comment]
Hi Erol,

v3.0.3 just released. Would you mind checking it again please?

Thanks

Paul

**Comment by iaroel** [comment]
Hi Paul,

It's working!

Thanks Paul and pricecurrent
