### ISSUE TITLE
File uploads

### ISSUE THREAD

**Issue by iaroel** [Softlabs/xero-laravel#6]
Hi Paul, Pricecurrent,

Is there a way to upload files?
Like http://developer.xero.com/documentation/api/attachments/

**Comment by pauljohnston** [comment]
Hi iaroel,

We currently have no plans to add attachments to this package.

I did find http://packalyst.com/packages/package/drawmyattention/xerolaravel - perhaps this may have what you need?

**Comment by iaroel** [comment]
Thanks Paul,

Will check it out.
