### ISSUE TITLE
Public cert does not exist:

### ISSUE THREAD

**Issue by rolandalla** [Softlabs/xero-laravel#7]
i get this error : exception 'Softlabs\XeroLaravel\PHPXero\XeroException' with message 'Public cert does not exist: ../config/xero/publickey.cer' 

The package is working all right if i test it into a controller .
But if i want to use the same function into a cron job im geting this error .

**Comment by pauljohnston** [comment]
Hi, this package is no longer maintained - try https://github.com/VentureCraft/xero-laravel

Regards

Paul
